# Generated by Django 5.2.11 on 2026-04-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_eats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="food_items/"),
        ),
    ]
